### PR TITLE
For tomasz

### PR DESCRIPTION
**Pull request by dolohow**

### CODE REVIEW

**Comment by Jarema** [comment]
Why not to use function name in godoc?

Thats how whole golang standard library is written and looks is considered idiomatic.

**Comment by dolohow** [comment]
Ok, then. For me it's just nuisance to repeat the name of the function every time. I'll fix that.

Anyway, I think it's better to implement those functions as middlewares. What do you think?

**Comment by Jarema** [comment]
It looks better in godoc :)

PROBABLY it will be better, but let's implement it like this first, and then refactor if we will find it more convinient.

**Comment by dolohow** [comment]
For sure it will be convenient, cause all error checking in route could be omitted.

**Pull request closed without merging**
